name: vHelp
main: com.perceivedev.vhelp.vHelp
version: 1.0
description: A custom help plugin that shows different help pages based on the player's permission
author: [Rayzr,EndureBlackout]
commands:
  help:
    description: Help command
    aliases: ?
    usage: "/help [page]"
  vHelp:
    description: vHelp management command
    usage: "/vHelp [reload]"
